dist: focal
language: ruby
cache: bundler
rvm:
  - 2.7
  - 2.6
  - 2.5
node_js:
  - 14
bundler_args: --without production
before_install:
  - yes | gem update --system --force
  - gem install bundler
script:
  - export RAILS_ENV=test
  - bundle exec rake db:schema:load
  - bundle exec rake test
