dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.6
  - 2.5
bundler_args: --without production
before_install:
  - gem update --system
  - gem install bundler
script:
  - export RAILS_ENV=test
  - bundle exec rake db:schema:load
  - bundle exec rake test